[package]
name = "task-queue"
version = "0.1.0"
authors = ["Ryan P. Brewster <RyanPBrewster@gmail.com>"]

[dependencies]
chrono = "0.4"
rusqlite = { version = "0.13", features = ["chrono"] }
structopt = "0.2"

[[bin]]
name = "rpb"
path = "src/bin/rpb.rs"
